### PR TITLE
Change labels in tabs example to avoid confusion

### PR DESCRIPTION
**Pull request by rnestler**
I played around a bit with relm and noticed that the tabs example didn't have any logic in it so I implemented the increment and decrement.

### CODE REVIEW

**Comment by antoyo** [comment]
Thanks for your work.
To be honest, I'm not sure I see the point of doing that.
This example shows how to use tabs, and does not intend to show any logic.
Any reason for adding it?

**Comment by rnestler** [comment]
>  Any reason for adding it?

I was slightly confused when I started the example and it had increment / decrement and a counter tab which didn't do anything.
But I understand if you prefer to keep the examples simple. But maybe it would be less confusing then if it wouldn't use increment / decrement buttons in the tabs but just something different.

**Comment by rnestler** [comment]
>  In that case, could you please change the UI so that it becomes less confusing?

I just renamed the labels, which should make it clear that there is no functionality.

**Comment by antoyo** [comment]
Thanks for your contribution.

**Pull request merged**
