### PR TITLE
Bump version recommended by README

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by antoyo** [comment]
Thanks for your contribution.

That was supposed to be done automatically by [this](https://github.com/antoyo/relm/blob/master/Cargo.toml#L59), so I'll investigate this issue.

**Comment by lpil** [comment]
Thank you :)

**Comment by onur** [comment]
Documentation is also recommending older version: https://github.com/antoyo/relm/blob/master/src/lib.rs#L31-L34

**Comment by antoyo** [comment]
onur: Thanks. I opened [an issue](https://github.com/antoyo/relm/issues/52) to get back the automatic version replacement.

**Pull request merged**
