### PR TITLE
Git dependency version

### PR DESCRIPTION
**Pull request by aknarts**
Full disclaimer I do not expect this to be merged but it is something I am actively maintaining so I might as well expose it.

I needed a direct github dependency because I am working on the github version of gtk-rs and family. So I created this fork and my branch. This will keep track of upstream changes and hopefully not be broken for a long time when upstream breaks. 

To use it as a dependency you can add
```cargo
relm = { git = "https://github.com/AchetaGames/relm.git", branch = "git"}
```
to your Cargo.toml 
Doing my best to merge both relm and gtk-rs changes into that branch.

### CODE REVIEW

**Comment by antoyo** [comment]
Yeah, I didn't want to bother maintaining 2 branches, because I always found it was a mess to do so in gtk-rs projects.
So, I'm not gonna merge this.

Let me know if there's anything I can do to make your life easier, though!

**Comment by aknarts** [comment]
I do not think there is anything from your side that is needed. I will keep the PR open for as long as I actively manage this just so people are able to find it if they want to.

**Comment by antoyo** [comment]
Maybe we could link it in the README or something?

**Comment by aknarts** [comment]
Honestly I am not sure how long I can keep this live and how long I will actually need this so this temporary solution is good for me for now... :D not looking for an endless project with little to no feedback or results... relm works great on the fixed versions of gtk..this is just for the special cases...

**Comment by aknarts** [comment]
Not maintaining this anymore, since gtk was released there is no real need

**Pull request closed without merging**
