### PR TITLE
Generate `glib::object::Object::new` instead of unsafe code

### PR DESCRIPTION
**Pull request by msrd0**
This removes all unsafe code that was previously being generated by the proc macro. Also simplifies the code a bit.

### CODE REVIEW

**Comment by antoyo** [comment]
Thanks for your contribution!

The CI now fails with some clippy warnings.

Can you please add the following at the crate root to silence those warnings?
```
#![allow(clippy::uninlined-format-args)]
```

**Comment by msrd0** [comment]
Should be fixed now

**Comment by antoyo** [comment]
I guess you'll need to add `allow(unknown_lints)` as well since it seems the clippy lint is not on stable yet.

**Comment by msrd0** [comment]
It looks like that didn't help. Maybe it would be sufficient to run clippy only on one Rust version?

**Comment by antoyo** [comment]
It seems like `unknown_lints` should come before the unknown lint in the list.

**Comment by msrd0** [comment]
Interesting, I didn't know the order had any effect

**Comment by antoyo** [comment]
Thanks!

**Pull request merged**
